#Generated for Project Metro 
server:
  port: 9090
  
spring:
  profiles:
    active:
    - prod
    
  datasource:
    url: jdbc:mysql://localhost:3307/db_travelagency
    username: root
    password: root
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
